### ISSUE TITLE
InternalOAuthError: failed to fetch user profile  

### ISSUE THREAD

**Issue by ghost** [Aquilio/05-07-18-feathersjs-and-google-oauth2#1]
i have following and test apps, but i got the error like this:
InternalOAuthError: failed to fetch user profile
    at C:\DevOps\feathers\feathers-google\node_modules\passport-google-oauth2\lib\oauth2.js:92:28
    at passBackControl (C:\DevOps\feathers\feathers-google\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\DevOps\feathers\feathers-google\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

how to fix it, thanks

**Comment by ghost** [comment]
The problem is solved., close it

**Comment by alexisabril** [comment]
@taufankiki Apologies for the late response! Glad to hear the issue has been resolved. If there's anything you found that can be improved, don't hesitate to let me know.
